language: node_js
node_js:
  - 16
cache:
  directories:
  - node_modules
script:
  - npm run web-prod
deploy:
  provider: pages
  cleanup: false
  github_token: $TRAVIS_TOKEN
  edge: true
  local_dir: dist
  keep_history: true
  on:
    branch: master